# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acompose < Formula
  desc "Run your docker-compose.yml on Apple's container CLI"
  homepage "https://acompose.pages.dev"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.1/acompose_0.1.1_darwin_amd64.tar.gz"
      sha256 "ca816f55c0066c53b6cc4ff64dc537b9257485de3c2c7678ce2b3a857e394e93"

      define_method(:install) do
        bin.install "acompose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.1/acompose_0.1.1_darwin_arm64.tar.gz"
      sha256 "3503634108c2bb52117a60ef26c6a2817aee96ffb7f9d2163e01d3def8bdde91"

      define_method(:install) do
        bin.install "acompose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.1/acompose_0.1.1_linux_amd64.tar.gz"
      sha256 "244bd8ad2df372545a401ef645bdce2b7c7e4c10e930f7e001a94aec53b92049"
      define_method(:install) do
        bin.install "acompose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.1/acompose_0.1.1_linux_arm64.tar.gz"
      sha256 "6b9fc439d483f24a3fb918ef6518fa693ecf3ea6b86d97ae42b90dede164a075"
      define_method(:install) do
        bin.install "acompose"
      end
    end
  end

  test do
    system "#{bin}/acompose", "version"
  end
end
