# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acompose < Formula
  desc "Run your docker-compose.yml on Apple's container CLI"
  homepage "https://acompose.pages.dev"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.4/acompose_0.1.4_darwin_amd64.tar.gz"
      sha256 "e92fb514aed0835276cedc0682fab49ed4d2679c91f41e40ff3afe6b96b6979f"

      define_method(:install) do
        bin.install "acompose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.4/acompose_0.1.4_darwin_arm64.tar.gz"
      sha256 "b592374c80e836a681cb70746f2bfb232d44dcdcb738f021ff458e996f070a5c"

      define_method(:install) do
        bin.install "acompose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.4/acompose_0.1.4_linux_amd64.tar.gz"
      sha256 "1fed51bd2118b3d339b928ebfaddd7bd7ce856cf408154e79462b72e80fe40a4"
      define_method(:install) do
        bin.install "acompose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/htlin222/acompose/releases/download/v0.1.4/acompose_0.1.4_linux_arm64.tar.gz"
      sha256 "1c5ffac6c9f42b4e89cc9dc62a825d4db3dec539714f4c0bb8d3867e7d27c898"
      define_method(:install) do
        bin.install "acompose"
      end
    end
  end

  test do
    system "#{bin}/acompose", "version"
  end
end
